# Generated by Django 4.2.2 on 2024-01-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
