# Generated by Django 4.2.2 on 2024-01-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_beneficiary_joined_date_beneficiary_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='pobox',
            field=models.IntegerField(null=True),
        ),
    ]
